USE [master]
GO
/****** Object:  Database [Sales_OLAP]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE DATABASE [Sales_OLAP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Sales_OLAP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Sales_OLAP.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Sales_OLAP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Sales_OLAP_log.ldf' , SIZE = 270336KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Sales_OLAP] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Sales_OLAP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Sales_OLAP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Sales_OLAP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Sales_OLAP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Sales_OLAP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Sales_OLAP] SET ARITHABORT OFF 
GO
ALTER DATABASE [Sales_OLAP] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Sales_OLAP] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Sales_OLAP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Sales_OLAP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Sales_OLAP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Sales_OLAP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Sales_OLAP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Sales_OLAP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Sales_OLAP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Sales_OLAP] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Sales_OLAP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Sales_OLAP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Sales_OLAP] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Sales_OLAP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Sales_OLAP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Sales_OLAP] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Sales_OLAP] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Sales_OLAP] SET RECOVERY FULL 
GO
ALTER DATABASE [Sales_OLAP] SET  MULTI_USER 
GO
ALTER DATABASE [Sales_OLAP] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Sales_OLAP] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Sales_OLAP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Sales_OLAP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Sales_OLAP] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Sales_OLAP] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Sales_OLAP', N'ON'
GO
ALTER DATABASE [Sales_OLAP] SET QUERY_STORE = ON
GO
ALTER DATABASE [Sales_OLAP] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Sales_OLAP]
GO
/****** Object:  Table [dbo].[DimCustomer]    Script Date: 4/21/2026 12:50:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimCustomer](
	[CustomerSK] [int] IDENTITY(1,1) NOT NULL,
	[customerBK] [int] NULL,
	[FName] [nvarchar](50) NULL,
	[LName] [nvarchar](50) NULL,
	[phone] [nvarchar](20) NULL,
	[email] [nvarchar](100) NULL,
	[gender_BK] [int] NULL,
	[genderName] [nvarchar](20) NULL,
	[SSCode] [varchar](5) NULL,
	[start_date] [datetime] NULL,
	[End_date] [datetime] NULL,
	[iscurrent] [bit] NULL,
 CONSTRAINT [PK__DimCusto__A4AF97EBE37683D5] PRIMARY KEY CLUSTERED 
(
	[CustomerSK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DimDate]    Script Date: 4/21/2026 12:50:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimDate](
	[DateSK] [int] NOT NULL,
	[Date] [date] NOT NULL,
	[Day] [char](2) NOT NULL,
	[DaySuffix] [varchar](4) NOT NULL,
	[DayOfWeek] [varchar](9) NOT NULL,
	[DOWInMonth] [tinyint] NOT NULL,
	[DayOfYear] [int] NOT NULL,
	[WeekOfYear] [tinyint] NOT NULL,
	[WeekOfMonth] [tinyint] NOT NULL,
	[Month] [char](2) NOT NULL,
	[MonthName] [varchar](9) NOT NULL,
	[Quarter] [tinyint] NOT NULL,
	[QuarterName] [varchar](6) NOT NULL,
	[Year] [char](4) NOT NULL,
	[StandardDate] [varchar](10) NULL,
	[HolidayText] [varchar](50) NULL,
	[FiscalDay] [char](2) NULL,
	[FiscalMonth] [char](2) NULL,
	[FiscalMonthName] [varchar](9) NULL,
	[FiscalQuarter] [tinyint] NULL,
	[FiscalQuarterName] [varchar](6) NULL,
	[FiscalYear] [char](4) NULL,
 CONSTRAINT [PK_DimDate] PRIMARY KEY CLUSTERED 
(
	[DateSK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DimProduct]    Script Date: 4/21/2026 12:50:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimProduct](
	[ProductSK] [int] IDENTITY(1,1) NOT NULL,
	[productBK] [int] NULL,
	[productName] [nvarchar](100) NULL,
	[productPrice] [decimal](10, 2) NULL,
	[subcategoryID_BK] [int] NULL,
	[subcategoryName] [nvarchar](100) NULL,
	[categoryID_BK] [int] NULL,
	[categoryName] [nvarchar](100) NULL,
	[SSCode] [varchar](5) NULL,
	[start_date] [datetime] NULL,
	[End_date] [datetime] NULL,
	[iscurrent] [bit] NULL,
 CONSTRAINT [PK__DimProdu__B40D13B03FC24DB9] PRIMARY KEY CLUSTERED 
(
	[ProductSK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DimSaleMan]    Script Date: 4/21/2026 12:50:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimSaleMan](
	[SalesManSK] [int] IDENTITY(1,1) NOT NULL,
	[salesmanBK] [int] NULL,
	[FName] [nvarchar](50) NULL,
	[LName] [nvarchar](50) NULL,
	[phone] [nvarchar](20) NULL,
	[email] [nvarchar](100) NULL,
	[addressID_BK] [int] NULL,
	[streetAddress] [nvarchar](255) NULL,
	[city] [nvarchar](100) NULL,
	[state] [nvarchar](50) NULL,
	[zipcode] [nvarchar](20) NULL,
	[SSCode] [varchar](5) NULL,
	[start_date] [datetime] NULL,
	[End_date] [datetime] NULL,
	[iscurrent] [bit] NULL,
 CONSTRAINT [PK__DimSaleM__2A199F1AF8D14187] PRIMARY KEY CLUSTERED 
(
	[SalesManSK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DimTime]    Script Date: 4/21/2026 12:50:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimTime](
	[TimeSK] [int] IDENTITY(1,1) NOT NULL,
	[Time] [time](0) NOT NULL,
	[Hour] [char](2) NOT NULL,
	[MilitaryHour] [char](2) NOT NULL,
	[Minute] [char](2) NOT NULL,
	[Second] [char](2) NOT NULL,
	[AmPm] [char](2) NOT NULL,
	[StandardTime] [char](11) NULL,
 CONSTRAINT [PK_DimTime] PRIMARY KEY CLUSTERED 
(
	[TimeSK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Fact_sales]    Script Date: 4/21/2026 12:50:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Fact_sales](
	[Fact_SK] [int] IDENTITY(1,1) NOT NULL,
	[customerID_FK] [int] NULL,
	[productID_FK] [int] NULL,
	[salesmanID_FK] [int] NULL,
	[orderdate_FK] [int] NULL,
	[ordertime_FK] [int] NULL,
	[orderID_BK] [int] NULL,
	[orderDetailsID_BK] [int] NULL,
	[totalPrice] [int] NULL,
	[quantity] [int] NULL,
	[loadedtime] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Fact_SK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[meta_control_table]    Script Date: 4/21/2026 12:50:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[meta_control_table](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[source_table] [nvarchar](50) NOT NULL,
	[last_load_date] [datetime] NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_dim_Time_HolidayText]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_dim_Time_HolidayText] ON [dbo].[DimDate]
(
	[HolidayText] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_DimDate_Date]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IDX_DimDate_Date] ON [dbo].[DimDate]
(
	[Date] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_DimDate_Day]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimDate_Day] ON [dbo].[DimDate]
(
	[Day] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_DimDate_DayOfWeek]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimDate_DayOfWeek] ON [dbo].[DimDate]
(
	[DayOfWeek] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_DimDate_DayOfYear]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimDate_DayOfYear] ON [dbo].[DimDate]
(
	[DayOfYear] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_DimDate_DOWInMonth]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimDate_DOWInMonth] ON [dbo].[DimDate]
(
	[DOWInMonth] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_DimDate_FiscalMonth]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimDate_FiscalMonth] ON [dbo].[DimDate]
(
	[FiscalMonth] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_DimDate_FiscalMonthName]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimDate_FiscalMonthName] ON [dbo].[DimDate]
(
	[MonthName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_DimDate_FiscalQuarter]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimDate_FiscalQuarter] ON [dbo].[DimDate]
(
	[FiscalQuarter] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_DimDate_FiscalQuarterName]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimDate_FiscalQuarterName] ON [dbo].[DimDate]
(
	[FiscalQuarterName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_DimDate_FiscalYear]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimDate_FiscalYear] ON [dbo].[DimDate]
(
	[FiscalYear] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_DimDate_Month]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimDate_Month] ON [dbo].[DimDate]
(
	[Month] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_DimDate_MonthName]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimDate_MonthName] ON [dbo].[DimDate]
(
	[MonthName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_DimDate_Quarter]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimDate_Quarter] ON [dbo].[DimDate]
(
	[Quarter] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_DimDate_QuarterName]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimDate_QuarterName] ON [dbo].[DimDate]
(
	[QuarterName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_DimDate_WeekOfMonth]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimDate_WeekOfMonth] ON [dbo].[DimDate]
(
	[WeekOfMonth] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_DimDate_WeekOfYear]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimDate_WeekOfYear] ON [dbo].[DimDate]
(
	[WeekOfYear] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_DimDate_Year]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimDate_Year] ON [dbo].[DimDate]
(
	[Year] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_DimTime_AmPm]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimTime_AmPm] ON [dbo].[DimTime]
(
	[AmPm] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_DimTime_Hour]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimTime_Hour] ON [dbo].[DimTime]
(
	[Hour] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_DimTime_MilitaryHour]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimTime_MilitaryHour] ON [dbo].[DimTime]
(
	[MilitaryHour] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_DimTime_Minute]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimTime_Minute] ON [dbo].[DimTime]
(
	[Minute] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_DimTime_Second]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimTime_Second] ON [dbo].[DimTime]
(
	[Second] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_DimTime_StandardTime]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE NONCLUSTERED INDEX [IDX_DimTime_StandardTime] ON [dbo].[DimTime]
(
	[StandardTime] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_DimTime_Time]    Script Date: 4/21/2026 12:50:22 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IDX_DimTime_Time] ON [dbo].[DimTime]
(
	[Time] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DimCustomer] ADD  CONSTRAINT [DF_DimCustomer_start_date]  DEFAULT (getdate()) FOR [start_date]
GO
ALTER TABLE [dbo].[DimProduct] ADD  CONSTRAINT [DF_DimProduct_start_date]  DEFAULT (getdate()) FOR [start_date]
GO
ALTER TABLE [dbo].[DimSaleMan] ADD  CONSTRAINT [DF_DimSaleMan_start_date]  DEFAULT (getdate()) FOR [start_date]
GO
ALTER TABLE [dbo].[DimTime]  WITH CHECK ADD  CONSTRAINT [FK_Fact_sales_DimTime] FOREIGN KEY([TimeSK])
REFERENCES [dbo].[DimTime] ([TimeSK])
GO
ALTER TABLE [dbo].[DimTime] CHECK CONSTRAINT [FK_Fact_sales_DimTime]
GO
ALTER TABLE [dbo].[Fact_sales]  WITH CHECK ADD  CONSTRAINT [FK__Fact_sale__custo__4316F928] FOREIGN KEY([customerID_FK])
REFERENCES [dbo].[DimCustomer] ([CustomerSK])
GO
ALTER TABLE [dbo].[Fact_sales] CHECK CONSTRAINT [FK__Fact_sale__custo__4316F928]
GO
ALTER TABLE [dbo].[Fact_sales]  WITH CHECK ADD  CONSTRAINT [FK__Fact_sale__produ__440B1D61] FOREIGN KEY([productID_FK])
REFERENCES [dbo].[DimProduct] ([ProductSK])
GO
ALTER TABLE [dbo].[Fact_sales] CHECK CONSTRAINT [FK__Fact_sale__produ__440B1D61]
GO
ALTER TABLE [dbo].[Fact_sales]  WITH CHECK ADD  CONSTRAINT [FK__Fact_sale__sales__44FF419A] FOREIGN KEY([salesmanID_FK])
REFERENCES [dbo].[DimSaleMan] ([SalesManSK])
GO
ALTER TABLE [dbo].[Fact_sales] CHECK CONSTRAINT [FK__Fact_sale__sales__44FF419A]
GO
USE [master]
GO
ALTER DATABASE [Sales_OLAP] SET  READ_WRITE 
GO
